apiVersion: apps/v1
kind: Deployment
metadata:
  name: jakartaee-cafe
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jakartaee-cafe
  template:
    metadata:
      name: jakartaee-cafe
      labels:
        app: jakartaee-cafe
    spec:
      containers:
      - name: jakartaee-cafe
        env:
          - name: POSTGRES_SERVER
            value: "jakartaee-cafe-db-<your suffix>.postgres.database.azure.com"        
          - name: POSTGRES_USER
            value: "postgres"
          - name: POSTGRES_PASSWORD
            value: "Secret123!"
        image: <your Docker Hub account>/jakartaee-cafe:v1
---
apiVersion: v1
kind: Service
metadata:
  name: jakartaee-cafe
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 9080
    - name: https
      port: 443
      targetPort: 9443  
  selector:
    app: jakartaee-cafe
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jakartaee-cafe
  annotations:
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"    
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: 
            name: jakartaee-cafe
            port:
              number: 80
      - path: /
        pathType: Prefix
        backend:
          service:
            name: jakartaee-cafe
            port:
              number: 443
