apiVersion: apps/v1
kind: Deployment
metadata:
  name: jakartaee-cafe
  namespace: default
  labels:
    app: jakartaee-cafe
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jakartaee-cafe
  template:
    metadata:
      name: jakartaee-cafe
      labels:
        app: jakartaee-cafe
    spec:
      containers:
      - name: jakartaee-cafe
        env:
          - name: POSTGRES_SERVER
            value: "jakartaee-cafe-db-<your suffix>.postgres.database.azure.com"
          - name: POSTGRES_USER
            value: "postgres"
          - name: POSTGRES_PASSWORD
            value: "Secret123!"
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: "http://otel-collector"
          - name: OTEL_EXPORTER_OTLP_PROTOCOL
            value: "http/protobuf"
          - name: OTEL_SDK_DISABLED
            value: "false"
          - name: OTEL_SERVICE_NAME
            value: "jakartaee-cafe"
        image: <your Docker Hub account>/jakartaee-cafe:v2
        ports:
          - name: http
            containerPort: 9080
            protocol: TCP
          - name: https
            containerPort: 9443
            protocol: TCP        
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 9080
          initialDelaySeconds: 15
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 2
        livenessProbe:
          httpGet:
            path: /health/live
            port: 9080
          initialDelaySeconds: 15
          periodSeconds: 60
          timeoutSeconds: 10
          failureThreshold: 3        
---
apiVersion: v1
kind: Service
metadata:
  name: jakartaee-cafe
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 9080
      protocol: TCP
    - name: https
      port: 443
      targetPort: 9443
      protocol: TCP      
  selector:
    app: jakartaee-cafe
