{
 "title": "JakartaEE-Cafe-Metrics-V1",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "pod",
    "label": "pod",
    "query": "base_cpu_processCpuLoad_percent"
   },
   {
    "name": "dur",
    "label": "moving average",
    "query": "[1m],[5m],[10m],[30m],[1h],[1d],[7d]"
   },
   { "name": "heapUsageThreshold", "label": "Heap Usage Threshold (%)", "query": "10,20,30,40,50,60,70,80,90,100" },
   {
    "name": "maxHeapUsageProjection",
    "label": "Max Heap Usage Projection (hours)",
    "query": "1"
   },
   { "name": "cpuDur", "query": "[1m]" },
   {
    "name": "garbageCollectionThreshold",
    "label": "Garbage Collection Threshold (%)",
    "query": "10,20,30,40,50,60,70,80,90,100"
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Available CPUs",
     "type": "table",
     "description": "The total number of CPU threads available to the JVM.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "base_cpu_availableProcessors{pod=~`[[pod]]`}",
       "legendFormat": "pod: {{pod}}, instance: {{instance}}"
      }
     ]
    },
    {
     "title": "Process CPU Time",
     "type": "graph",
     "description": "The portion of CPU available to each Liberty instance that has been used within the last [[dur]] on average.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "rate(base_cpu_processCpuTime_seconds{pod=~`[[pod]]`}[[cpuDur]]) / base_cpu_availableProcessors",
       "legendFormat": "pod: {{pod}}, instance: {{instance}}"
      }
     ]
    },
    {
     "title": "CPU System Load",
     "type": "graph",
     "description": "For CPUs Liberty is running on, the average number of runnable entities that have been scheduled or executed by the system, over the last minute.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "base_cpu_systemLoadAverage{pod=~`[[pod]]`}",
       "legendFormat": "pod: {{pod}}, instance: {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory Heap",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pods Above [$heapUsageThreshold%] Heap Usage",
     "type": "table",
     "description": "Pods that are currently utilizing more than [$heapUsageThreshold%] of their configured maximum heap size.",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "base_memory_usedHeap_bytes{pod=~`[[pod]]`} / base_memory_maxHeap_bytes{pod=~`[[pod]]`} > [[heapUsageThreshold]]/100"
      }
     ]
    },
    {
     "title": "Increasing Heap Usage Trend Based on Last [[dur]]",
     "type": "table",
     "description": "Pods with an increase in heap usage within the last [[dur]].",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 6 },
     "targets": [
      {
       "expr": "deriv(base_memory_usedHeap_bytes{pod=~`[[pod]]`}[[dur]]) > 0"
      }
     ]
    },
    {
     "title": "Servers That May Reach Max Heap Usage Within [$maxHeapUsageProjection hour(s)] Based on Last [[dur]]",
     "type": "table",
     "description": "Pods projected to reach their maximum heap size within [$maxHeapUsageProjection hour(s)] based on  data over the last [[dur]].",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 6 },
     "targets": [
      {
       "expr": "predict_linear(base_memory_usedHeap_bytes{pod=~`[[pod]]`}[[dur]], [[maxHeapUsageProjection]] * 3600) > base_memory_maxHeap_bytes{pod=~`[[pod]]`}"
      }
     ]
    },
    {
     "title": "Configured Maximum Heap Size",
     "type": "table",
     "description": "A pod's maximum heap size.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "base_memory_maxHeap_bytes{pod=~`[[pod]]`}"
      }
     ]
    },
    {
     "title": "Heap Usage Percentage",
     "type": "graph",
     "description": "The percentage of heap memory currently in use.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "base_memory_usedHeap_bytes{pod=~`[[pod]]`} / base_memory_maxHeap_bytes{pod=~`[[pod]]`}",
       "legendFormat": "pod: {{pod}}, instance: {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "REST",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Slowest REST Resources Over Last [[dur]] by Average Response Time",
     "type": "table",
     "description": "The average response time for requests made to a particular REST resource method, based on data over the last [[dur]].",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "avg(rate(base_REST_request_elapsedTime_seconds{pod=~`[[pod]]`}[[dur]]) / rate(base_REST_request_total{pod=~`[[pod]]`}[[dur]])) by (class, method) > 0"
      }
     ]
    },
    {
     "title": "REST Request Count Over Last [[dur]]",
     "type": "graph",
     "description": "The number of visits made to a REST resource instance within the past [[dur]].",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(base_REST_request_total{pod=~`[[pod]]`}[[dur]])",
       "legendFormat": "pod: {{pod}}, class: {{class}}, method: {{method}}"
      }
     ]
    },
    {
     "title": "Average Response Time per REST Request Over Last [[dur]] ",
     "type": "graph",
     "description": "The average response time for a request made to a REST resource instance, based on data over the last [[dur]].",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(base_REST_request_elapsedTime_seconds{pod=~`[[pod]]`}[[dur]])/rate(base_REST_request_total{pod=~`[[pod]]`}[[dur]])",
       "legendFormat": "pod: {{pod}}, class: {{class}}, method: {{method}}"
      }
     ]
    },
    {
     "title": "Request Count by REST Resource Over Last [[dur]]",
     "type": "graph",
     "description": "The sum of visits to a particular REST resource over all servers, based on data over the last [[dur]].",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(base_REST_request_total{pod=~`[[pod]]`}[[dur]])) by (class, method)",
       "legendFormat": "class: {{class}}, method: {{method}}"
      }
     ]
    },
    {
     "title": "Average Response Time per Request Over Last [[dur]] by REST Resource",
     "type": "graph",
     "description": "The average response time for requests made to a particular REST resource method, based on data over the last [[dur]].",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "avg(rate(base_REST_request_elapsedTime_seconds{pod=~`[[pod]]`}[[dur]]) / rate(base_REST_request_total{pod=~`[[pod]]`}[[dur]])) by (class, method)",
       "legendFormat": "class: {{class}}, method: {{method}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Servlets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Slowest Servlets Over Last [[dur]] by Average Response Time",
     "type": "table",
     "description": "The average response time for requests made to a particular servlet, across all servers, based on data over the last [[dur]].",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 4 },
     "targets": [
      {
       "expr": "avg(rate(vendor_servlet_responseTime_total_seconds{pod=~`[[pod]]`}[[dur]]) / rate(vendor_servlet_request_total{pod=~`[[pod]]`}[[dur]])) by (servlet) > 0"
      }
     ]
    },
    {
     "title": "Request Count Over Last [[dur]]",
     "type": "graph",
     "description": "The number of visits made to a servlet instance within the past [[dur]].",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(vendor_servlet_request_total{pod=~`[[pod]]`}[[dur]])",
       "legendFormat": "pod: {{pod}}, servlet: {{servlet}}, instance: {{instance}}"
      }
     ]
    },
    {
     "title": "Average Response Time per Request Over Last [[dur]] ",
     "type": "graph",
     "description": "The average response time for a request made to a servlet instance, based on data over the last [[dur]].",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(vendor_servlet_responseTime_total_seconds{pod=~`[[pod]]`}[[dur]])/rate(vendor_servlet_request_total{pod=~`[[pod]]`}[[dur]])",
       "legendFormat": "pod: {{pod}}, servlet: {{servlet}}, instance: {{instance}}"
      }
     ]
    },
    {
     "title": "Request Count by Servlet Over Last [[dur]]",
     "type": "graph",
     "description": "The sum of visits to a particular servlet over all servers, based on data over the last [[dur]].",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(vendor_servlet_request_total{pod=~`[[pod]]`}[[dur]])) by (servlet)",
       "legendFormat": "servlet: {{servlet}}"
      }
     ]
    },
    {
     "title": "Average Response Time per Request Over Last [[dur]] by Servlet",
     "type": "graph",
     "description": "The average response time for requests made to a particular servlet, across all servers, based on data over the last [[dur]].",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "avg(rate(vendor_servlet_responseTime_total_seconds{pod=~`[[pod]]`}[[dur]]) / rate(vendor_servlet_request_total{pod=~`[[pod]]`}[[dur]])) by (servlet)",
       "legendFormat": "servlet: {{servlet}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Connection Pool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connections Used Over Last [[dur]]",
     "type": "table",
     "description": "The total number of connection requests that were used over the last [[dur]]. Any connections that are currently in use are not included in this total.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 5 },
     "targets": [
      {
       "expr": "increase(vendor_connectionpool_usedConnections_total{pod=~`[[pod]]`}[[dur]]) > 0"
      }
     ]
    },
    {
     "title": "Connection Requests Queued Over Last [[dur]]",
     "type": "table",
     "description": "The total number of connection requests that waited for a connection because of a full connection pool over the last [[dur]].",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 5 },
     "targets": [
      {
       "expr": "increase(vendor_connectionpool_queuedRequests_total{pod=~`[[pod]]`}[[dur]]) > 0"
      }
     ]
    },
    {
     "title": "Average Time Usage per Connection Over Last [[dur]]",
     "type": "graph",
     "description": "The average time any used connection was put in use, based on data over the last [[dur]].",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(vendor_connectionpool_inUseTime_total_seconds{pod=~`[[pod]]`}[[dur]]) / rate(vendor_connectionpool_usedConnections_total{pod=~`[[pod]]`}[[dur]]) > 0",
       "legendFormat": "datasource: {{datasource}}, pod: {{pod}}, instance: {{instance}}"
      }
     ]
    },
    {
     "title": "Average Wait Time per Queued Connection Request Over Last [[dur]]",
     "type": "graph",
     "description": "The average wait time for any queued connection request, based on data over the last [[dur]].",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(vendor_connectionpool_waitTime_total_seconds{pod=~`[[pod]]`}[[dur]]) / rate(vendor_connectionpool_queuedRequests_total{pod=~`[[pod]]`}[[dur]]) > 0",
       "legendFormat": "datasource: {{datasource}}, pod: {{pod}}, instance: {{instance}}"
      }
     ]
    },
    {
     "title": "Managed Connections",
     "type": "graph",
     "description": "The sum of managed connections in the free, shared, and unshared pools.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "vendor_connectionpool_managedConnections{pod=~`[[pod]]`}",
       "legendFormat": "datasource: {{datasource}}, pod: {{pod}}, instance: {{instance}}"
      }
     ]
    },
    {
     "title": "Free Connections",
     "type": "graph",
     "description": "The number of managed connections in the free pool.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "vendor_connectionpool_freeConnections{pod=~`[[pod]]`}",
       "legendFormat": "datasource: {{datasource}}, pod: {{pod}}, instance: {{instance}}"
      }
     ]
    },
    {
     "title": "Connection Handles",
     "type": "graph",
     "description": "The number of connections that are in use. This number might include multiple connections that are shared from a single managed connection.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "vendor_connectionpool_connectionHandles{pod=~`[[pod]]`}",
       "legendFormat": "datasource: {{datasource}}, pod: {{pod}}, instance: {{instance}}"
      }
     ]
    },
    {
     "title": "Create Total",
     "type": "graph",
     "description": "The total number of managed connections created since the pool was created.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "vendor_connectionpool_create_total{pod=~`[[pod]]`}",
       "legendFormat": "datasource: {{datasource}}, pod: {{pod}}, instance: {{instance}}"
      }
     ]
    },
    {
     "title": "Destroy Total",
     "type": "graph",
     "description": "The total number of managed connections destroyed since the pool was created.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "vendor_connectionpool_destroy_total{pod=~`[[pod]]`}",
       "legendFormat": "datasource: {{datasource}}, pod: {{pod}}, instance: {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active Sessions",
     "type": "graph",
     "description": "A session is considered active if the application server is processing a request that uses that user session.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "vendor_session_activeSessions{pod=~`[[pod]]`}",
       "legendFormat": "appname: {{appname}}, pod: {{pod}}, instance: {{instance}}"
      }
     ]
    },
    {
     "title": "Live Sessions",
     "type": "graph",
     "description": "A session is considered live if the session is loaded into memory by the application server.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "vendor_session_liveSessions{pod=~`[[pod]]`}",
       "legendFormat": "appname: {{appname}}, pod: {{pod}}, instance: {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Threadpools",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Largest Threadpool Sizes Over Last [[dur]]",
     "type": "table",
     "description": "The size of the Default Executor thread pool in each instance.",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "max_over_time(vendor_threadpool_size{pod=~`[[pod]]`}[[dur]])"
      }
     ]
    },
    {
     "title": "Active Threads",
     "type": "graph",
     "description": "The number of threads that are actively running tasks.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "vendor_threadpool_activeThreads{pod=~`[[pod]]`}",
       "legendFormat": "pool: {{pool}}, pod: {{pod}}, instance: {{instance}}"
      }
     ]
    },
    {
     "title": "Threadpool Size",
     "type": "graph",
     "description": "The size of the Default Executor thread pool in each instance.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "vendor_threadpool_size{pod=~`[[pod]]`}",
       "legendFormat": "pool: {{pool}}, pod: {{pod}}, instance: {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Garbage Collection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pods With > [$garbageCollectionThreshold]% of Time Spent Garbage Collecting During Last [[dur]]",
     "type": "table",
     "description": "Pods that spent more than [$garbageCollectionThreshold%] of the time garbage collecting, during the last [[dur]].",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "sum(rate(base_gc_time_seconds{pod=~`[[pod]]`}[[dur]])) by (namespace, pod, service) > [[garbageCollectionThreshold]] / 100"
      }
     ]
    },
    {
     "title": "Most Time Spent on Garbage Collection Over Last [[dur]]",
     "type": "table",
     "description": "The portion of time an instance spent on a specific type of garbage collection, based on data over the last [[dur]]. ",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
     "targets": [
      {
       "expr": "rate(base_gc_time_seconds{pod=~`[[pod]]`}[[dur]]) > 0"
      }
     ]
    },
    {
     "title": "Time per Garbage Collection Cycle [[dur]] moving average",
     "type": "graph",
     "description": "The average time an instance took on a specific type of garbage collection, based on data over the last [[dur]].",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(base_gc_time_seconds{pod=~`[[pod]]`}[[dur]]) / rate(base_gc_total{pod=~`[[pod]]`}[[dur]])",
       "legendFormat": "pod: {{pod}}, instance: {{instance}}, name: {{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Other JVM Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "JVM Uptime",
     "type": "table",
     "description": "The time elapsed since the start of the JVM.",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "base_jvm_uptime_seconds{pod=~`[[pod]]`}"
      }
     ]
    }
   ]
  }
 ]
}