receivers:
  otlp:
    protocols:
      grpc: 
        endpoint: 0.0.0.0:4317
      http: 
        endpoint: 0.0.0.0:4318

processors:
  batch:
    send_batch_max_size: 100
    send_batch_size: 10
    timeout: 10s

exporters:
  debug:
    verbosity: detailed
  azuremonitor:
    connection_string: ${env:APPLICATIONINSIGHTS_CONNECTION_STRING}

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [azuremonitor, debug]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [azuremonitor, debug]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [azuremonitor, debug]
