apiVersion: openliberty.io/v1beta1
kind: OpenLibertyApplication
metadata:
  name: jakartaee-cafe
spec:
  replicas: 2
  applicationImage: <your Docker Hub account>/jakartaee-cafe:v3
  env:
    - name: POSTGRES_SERVER
      value: "jakartaee-cafe-db-<your suffix>.postgres.database.azure.com"        
    - name: POSTGRES_USER
      value: "postgres@jakartaee-cafe-db-<your suffix>"
    - name: POSTGRES_PASSWORD
      value: "Secret123!"
  service:
    type: LoadBalancer
    ports:
      - port: 80
        targetPort: 9080
